### ISSUE TITLE
tappy cli tool fails for a directory where some tap files have the tap version declaration and some not

### ISSUE THREAD

**Issue by timsampsoncujo** [python-tap/tappy#113]
```shell
$ cat *.tap
TAP version 13
1..3
ok 1 - Input file opened
ok 2 - First line of the input valid
ok 3 - Read the rest of the file
1..3
ok 1 - Input file opened
ok 2 - First line of the input valid
ok 3 - Read the rest of the file
$ tappy .
Traceback (most recent call last):
  File "/usr/bin/tappy", line 11, in <module>
    load_entry_point('tap.py==3.0', 'console_scripts', 'tappy')()
  File "/usr/lib/python3/dist-packages/tap/main.py", line 15, in main
    suite = build_suite(args)
  File "/usr/lib/python3/dist-packages/tap/main.py", line 28, in build_suite
    suite = loader.load(args.files)
  File "/usr/lib/python3/dist-packages/tap/loader.py", line 29, in load
    self._find_tests_in_directory(filepath, suite)
  File "/usr/lib/python3/dist-packages/tap/loader.py", line 64, in _find_tests_in_directory
    suite.addTest(self.load_suite_from_file(filepath))
  File "/usr/lib/python3/dist-packages/tap/loader.py", line 47, in load_suite_from_file
    return self._load_lines(filename, line_generator, suite, rules)
  File "/usr/lib/python3/dist-packages/tap/loader.py", line 69, in _load_lines
    for line in line_generator:
  File "/usr/lib/python3/dist-packages/tap/parser.py", line 116, in parse
    yield self.parse_line(line.rstrip(), fh_new)
  File "/usr/lib/python3/dist-packages/tap/parser.py", line 122, in parse_line
    return self._parse_result(True, match, fh)
  File "/usr/lib/python3/dist-packages/tap/parser.py", line 161, in _parse_result
    peek_match = self.yaml_block_start.match(fh.peek())
AttributeError: 'itertools.chain' object has no attribute 'peek'
$ nvim 1.tap
$ cat *.tap
1..3
ok 1 - Input file opened
ok 2 - First line of the input valid
ok 3 - Read the rest of the file
1..3
ok 1 - Input file opened
ok 2 - First line of the input valid
ok 3 - Read the rest of the file
$ tappy .
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
```

As I recall the tool will work fine also if both files include the version declaration

**Comment by timsampsoncujo** [comment]
This is fixed in master actually, it seems.
