### ISSUE TITLE
SyntaxError when pip installing in Python 3.6

### ISSUE THREAD

**Issue by chr15m** [python-tap/tappy#82]
Hi,

I tried to rule out local configuration issues but couldn't seem to find anything wrong. Here's what happens when I try to install tappy via pip:

```
$ pip install tappy
Collecting tappy
  Using cached https://files.pythonhosted.org/packages/bf/e6/26ee364e95d1fceb7291e8eb06cb7314e9c98ee11cedfebd92ade88e8f57/tappy-0.9.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8151gqbg/tappy/setup.py", line 76
        raise SystemExit, msg
                        ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-8151gqbg/tappy/
(virtualenv) $ pyenv local
3.6.6
(virtualenv) $ python --version
Python 3.6.6
(virtualenv) $ pip --version
pip 19.0 from .../virtualenv/lib/python3.6/site-packages/pip (python 3.6)
```

**Comment by chr15m** [comment]
Oh my god. Sorry, and thank you for the polite correction! :man_facepalming:

**Comment by mblayman** [comment]
No problem! Maybe I should put a note in the docs because it's a pretty easy thing to miss.

**Comment by chr15m** [comment]
I think it's enough that the correct install command is the first command listed on both github & readthedocs

This was a good reminder for me that software should not be build under high time pressure. :)
