### ISSUE TITLE
Test suite fails

### ISSUE THREAD

**Issue by rossburton** [python-tap/tappy#85]
With a fresh clone of git master:

```
$ python3 setup.py build
[ ... ]
$ python3 setup.py test
[ ... ]
======================================================================
ERROR: test_malformed_yaml (tap.tests.test_parser.TestParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ross/Local/mess/24/tappy/tap/tests/test_parser.py", line 399, in test_malformed_yaml
    for line in parser.parse_text(sample):
  File "/home/ross/Local/mess/24/tappy/tap/parser.py", line 116, in parse
    yield self.parse_line(line.rstrip(), fh_new)
  File "/home/ross/Local/mess/24/tappy/tap/parser.py", line 122, in parse_line
    return self._parse_result(True, match, fh)
  File "/home/ross/Local/mess/24/tappy/tap/parser.py", line 172, in _parse_result
    concat_yaml = self._extract_yaml_block(indent, fh)
  File "/home/ross/Local/mess/24/tappy/tap/parser.py", line 186, in _extract_yaml_block
    fh.next()
AttributeError: 'peekable' object has no attribute 'next'

======================================================================
ERROR: test_parses_yaml (tap.tests.test_parser.TestParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ross/Local/mess/24/tappy/tap/tests/test_parser.py", line 235, in test_parses_yaml
    for line in parser.parse_text(sample):
  File "/home/ross/Local/mess/24/tappy/tap/parser.py", line 116, in parse
    yield self.parse_line(line.rstrip(), fh_new)
  File "/home/ross/Local/mess/24/tappy/tap/parser.py", line 122, in parse_line
    return self._parse_result(True, match, fh)
  File "/home/ross/Local/mess/24/tappy/tap/parser.py", line 172, in _parse_result
    concat_yaml = self._extract_yaml_block(indent, fh)
  File "/home/ross/Local/mess/24/tappy/tap/parser.py", line 186, in _extract_yaml_block
    fh.next()
AttributeError: 'peekable' object has no attribute 'next'

======================================================================
ERROR: test_parses_yaml_more_complex (tap.tests.test_parser.TestParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ross/Local/mess/24/tappy/tap/tests/test_parser.py", line 304, in test_parses_yaml_more_complex
    for line in parser.parse_text(sample):
  File "/home/ross/Local/mess/24/tappy/tap/parser.py", line 116, in parse
    yield self.parse_line(line.rstrip(), fh_new)
  File "/home/ross/Local/mess/24/tappy/tap/parser.py", line 122, in parse_line
    return self._parse_result(True, match, fh)
  File "/home/ross/Local/mess/24/tappy/tap/parser.py", line 172, in _parse_result
    concat_yaml = self._extract_yaml_block(indent, fh)
  File "/home/ross/Local/mess/24/tappy/tap/parser.py", line 186, in _extract_yaml_block
    fh.next()
AttributeError: 'peekable' object has no attribute 'next'

======================================================================
ERROR: test_parses_yaml_no_end (tap.tests.test_parser.TestParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ross/Local/mess/24/tappy/tap/tests/test_parser.py", line 267, in test_parses_yaml_no_end
    for line in parser.parse_text(sample):
  File "/home/ross/Local/mess/24/tappy/tap/parser.py", line 116, in parse
    yield self.parse_line(line.rstrip(), fh_new)
  File "/home/ross/Local/mess/24/tappy/tap/parser.py", line 122, in parse_line
    return self._parse_result(True, match, fh)
  File "/home/ross/Local/mess/24/tappy/tap/parser.py", line 172, in _parse_result
    concat_yaml = self._extract_yaml_block(indent, fh)
  File "/home/ross/Local/mess/24/tappy/tap/parser.py", line 186, in _extract_yaml_block
    fh.next()
AttributeError: 'peekable' object has no attribute 'next'

----------------------------------------------------------------------
Ran 109 tests in 0.023s

FAILED (errors=4)
```

**Comment by mblayman** [comment]
I haven't used that method of testing in quite a while so I'm not surprised it's broken. I suspect that the `test_requires` is missing `more_itertools`. We normally run the test suite with tox, which installs all the needed requirements.
