### ISSUE TITLE
With more-itertools 7.2 tests break due to peakable behaviour changed

### ISSUE THREAD

**Issue by scarabeusiv** [python-tap/tappy#87]
```
[    6s] ======================================================================
[    6s] ERROR: test_malformed_yaml (tap.tests.test_parser.TestParser)
[    6s] ----------------------------------------------------------------------
[    6s] Traceback (most recent call last):
[    6s]   File "/home/abuild/rpmbuild/BUILD/tap.py-2.5/tap/tests/test_parser.py", line 399, in test_malformed_yaml
[    6s]     for line in parser.parse_text(sample):
[    6s]   File "/home/abuild/rpmbuild/BUILD/tap.py-2.5/tap/parser.py", line 116, in parse
[    6s]     yield self.parse_line(line.rstrip(), fh_new)
[    6s]   File "/home/abuild/rpmbuild/BUILD/tap.py-2.5/tap/parser.py", line 122, in parse_line
[    6s]     return self._parse_result(True, match, fh)
[    6s]   File "/home/abuild/rpmbuild/BUILD/tap.py-2.5/tap/parser.py", line 172, in _parse_result
[    6s]     concat_yaml = self._extract_yaml_block(indent, fh)
[    6s]   File "/home/abuild/rpmbuild/BUILD/tap.py-2.5/tap/parser.py", line 186, in _extract_yaml_block
[    6s]     fh.next()
[    6s] AttributeError: 'peekable' object has no attribute 'next'
[    6s] 
[    6s] ======================================================================
[    6s] ERROR: test_parses_yaml (tap.tests.test_parser.TestParser)
[    6s] ----------------------------------------------------------------------
[    6s] Traceback (most recent call last):
[    6s]   File "/home/abuild/rpmbuild/BUILD/tap.py-2.5/tap/tests/test_parser.py", line 235, in test_parses_yaml
[    6s]     for line in parser.parse_text(sample):
[    6s]   File "/home/abuild/rpmbuild/BUILD/tap.py-2.5/tap/parser.py", line 116, in parse
[    6s]     yield self.parse_line(line.rstrip(), fh_new)
[    6s]   File "/home/abuild/rpmbuild/BUILD/tap.py-2.5/tap/parser.py", line 122, in parse_line
[    6s]     return self._parse_result(True, match, fh)
[    6s]   File "/home/abuild/rpmbuild/BUILD/tap.py-2.5/tap/parser.py", line 172, in _parse_result
[    6s]     concat_yaml = self._extract_yaml_block(indent, fh)
[    6s]   File "/home/abuild/rpmbuild/BUILD/tap.py-2.5/tap/parser.py", line 186, in _extract_yaml_block
[    6s]     fh.next()
[    6s] AttributeError: 'peekable' object has no attribute 'next'
[    6s] 
[    6s] ======================================================================
[    6s] ERROR: test_parses_yaml_more_complex (tap.tests.test_parser.TestParser)
[    6s] ----------------------------------------------------------------------
[    6s] Traceback (most recent call last):
[    6s]   File "/home/abuild/rpmbuild/BUILD/tap.py-2.5/tap/tests/test_parser.py", line 304, in test_parses_yaml_more_complex
[    6s]     for line in parser.parse_text(sample):
[    6s]   File "/home/abuild/rpmbuild/BUILD/tap.py-2.5/tap/parser.py", line 116, in parse
[    6s]     yield self.parse_line(line.rstrip(), fh_new)
[    6s]   File "/home/abuild/rpmbuild/BUILD/tap.py-2.5/tap/parser.py", line 122, in parse_line
[    6s]     return self._parse_result(True, match, fh)
[    6s]   File "/home/abuild/rpmbuild/BUILD/tap.py-2.5/tap/parser.py", line 172, in _parse_result
[    6s]     concat_yaml = self._extract_yaml_block(indent, fh)
[    6s]   File "/home/abuild/rpmbuild/BUILD/tap.py-2.5/tap/parser.py", line 186, in _extract_yaml_block
[    6s]     fh.next()
[    6s] AttributeError: 'peekable' object has no attribute 'next'
[    6s] 
[    6s] ======================================================================
[    6s] ERROR: test_parses_yaml_no_end (tap.tests.test_parser.TestParser)
[    6s] ----------------------------------------------------------------------
[    6s] Traceback (most recent call last):
[    6s]   File "/home/abuild/rpmbuild/BUILD/tap.py-2.5/tap/tests/test_parser.py", line 267, in test_parses_yaml_no_end
[    6s]     for line in parser.parse_text(sample):
[    6s]   File "/home/abuild/rpmbuild/BUILD/tap.py-2.5/tap/parser.py", line 116, in parse
[    6s]     yield self.parse_line(line.rstrip(), fh_new)
[    6s]   File "/home/abuild/rpmbuild/BUILD/tap.py-2.5/tap/parser.py", line 122, in parse_line
[    6s]     return self._parse_result(True, match, fh)
[    6s]   File "/home/abuild/rpmbuild/BUILD/tap.py-2.5/tap/parser.py", line 172, in _parse_result
[    6s]     concat_yaml = self._extract_yaml_block(indent, fh)
[    6s]   File "/home/abuild/rpmbuild/BUILD/tap.py-2.5/tap/parser.py", line 186, in _extract_yaml_block
[    6s]     fh.next()
[    6s] AttributeError: 'peekable' object has no attribute 'next'
[    6s] 
[    6s] ----------------------------------------------------------------------
[    6s] Ran 109 tests in 0.014s
```

**Comment by mblayman** [comment]
Thanks for the report @scarabeusiv.

The test runner in CI was properly capturing the exit status code so this was failing, but I never noticed! Once CI reports back to green, I'll push out 2.6.1 to fix this.
